"""Add security enhancements and indexes

Revision ID: 7ef63e41c980
Revises: aa1d6cde7e7c
Create Date: 2025-06-19 00:13:41.561433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef63e41c980'
down_revision = 'aa1d6cde7e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_created_by'), 'game', ['created_by'], unique=False)
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    op.create_index('idx_game_stone', 'stone', ['game_id', 'stone_number'], unique=False)
    op.create_index(op.f('ix_stone_bidder_id'), 'stone', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_stone_game_id'), 'stone', ['game_id'], unique=False)
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'account_locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'created_at')
    op.drop_index(op.f('ix_stone_game_id'), table_name='stone')
    op.drop_index(op.f('ix_stone_bidder_id'), table_name='stone')
    op.drop_index('idx_game_stone', table_name='stone')
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_index(op.f('ix_game_created_by'), table_name='game')
    # ### end Alembic commands ###
